// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ValidRegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void validRegistration() {
    driver.get("https://codeforces.com/enter?back=%2Fprofile%2Flogin");
    driver.manage().window().setSize(new Dimension(910, 1033));
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.name("handle")).click();
    driver.findElement(By.name("handle")).sendKeys("Selenium_Testing");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("esha1923tasnia@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("esha1923tasnia");
    driver.findElement(By.name("passwordConfirmation")).click();
    driver.findElement(By.name("passwordConfirmation")).sendKeys("esha1923tasnia");
    driver.findElement(By.cssSelector(".submit")).click();
  }
}
